### ISSUE TITLE
Transparent or gradient background

### ISSUE THREAD

**Issue by bumbummen99** [tengbao/vanta#1]
Hey there,

i am using vanta in a new web-project with an already planned design. The design intends a gradient as the background. I want vanta to draw above that background (transparent) or to pass the gradient as backgroundGradient option. After a quick look to the code it seems like that will not be that easy.

Do you have an easy solution in mind or has anyone accomplished this before?

**Comment by tengbao** [comment]
Thanks for the feedback! This is now possible on ThreeJS effects, using: 
```
VANTA.BIRDS({
  el: "#your-element-selector",
  backgroundColor: 'transparent'
})
```

Or set the alpha yourself:

```
VANTA.BIRDS({
  el: "#your-element-selector",
  backgroundAlpha: '0.5'
})
```

**Comment by akuznets0v** [comment]
Heads up, setting backgroundColor: 'transparent' doesn't seem to play nice with three.js, 
continuously throws a warning:
THREE.Color: Unknown color transparent

**Comment by tengbao** [comment]
Good point. Fixed.

**Comment by AlexandraKlein** [comment]
`backgroundAlpha: 0` not enabled on HALO effect.

**Comment by Manishgupta200** [comment]
Thankyou very helpful for me
