### ISSUE TITLE
Low res rendering when width of page >=600 px

### ISSUE THREAD

**Issue by dbudwin** [tengbao/vanta#100]
## What

While viewing at a width >=600px the wave effect is very low resolution and appears pixelated and blurry.  When the width of the page <600px, it is crystal clear.  Below is a screenshot--I zoomed in a bit to enhance the blurriness.

<img width="945" alt="Screen Shot 2021-01-09 at 15 38 29" src="https://user-images.githubusercontent.com/15161181/104108207-c3e0f400-5290-11eb-9b06-0dd4490b0c54.png">

This strictly appears to be affected by the width, the height doesn't seem to trigger the blurriness.

## CodeSanbox

Resize the pane on the right showing the waves to be wider or narrower to see the effect switch between blurry and clear.

https://codesandbox.io/s/vanta-wave-blur-5un1z

## Video

Here is a screen capture of the issue: https://vimeo.com/498745302

**Comment by tengbao** [comment]
Try setting the `scale` and `scaleMobile` to 1. That seems to fix the issue.
