### ISSUE TITLE
Geometry is no longer a constructor in three.js r125

### ISSUE THREAD

**Issue by DustinBrett** [tengbao/vanta#101]
As mentioned in [this article](https://discourse.threejs.org/t/three-geometry-will-be-removed-from-core-with-r125/22401?fbclid=IwAR1IOA5w7__0rsliPSCo0STmy95JF3ewQqIsy9cWsNWEB539K96nVCjf2Ug), three.js has removed `THREE.Geometry` in [r125](https://github.com/mrdoob/three.js/releases/tag/r125). I recently tried to use WAVES with r125 and got the error `n.Geometry is not a constructor`.

It looks like this constructor is used quite a bit [in vanta](https://github.com/tengbao/vanta/search?q=THREE.Geometry).

I attempted to convert `Geometry` to `BufferGeometry` but I don't know enough about vertices or faces or any of that stuff so it quickly got out of hand for me.

My current "fix" is locking my three.js version at 0.124.0.

**Comment by tengbao** [comment]
Thanks for catching this! Yea, simple solution is just to rollback to an older version of threejs. I'll update the code later!

**Comment by rafaelpimpa** [comment]
Dependabot is now acknowledging vulnerabilities issues with threejs < r125 btw.

**Comment by naveennazimudeen** [comment]
When I uggraded to three@0.126.1, there was an error at destroy

![image](https://user-images.githubusercontent.com/20735539/112230039-87276680-8c0a-11eb-8e8f-c369571b3fa0.png)

**Comment by nicoan000** [comment]
The issue still exists for topology even if you rollback to 119 like the demo on the site shows. 

`vanta.topology.min.js:1 [VANTA] Init error TypeError: n is not a constructor`

import Head from 'next/head'
import { useEffect, useRef, useState } from "react";
import TOPOLOGY from 'vanta/dist/vanta.topology.min';
import * as THREE from "three";
import { css } from '@emotion/css';

/page
```
const style = css`
    min-height: 100vh;
    height: 100%;
    width: 100%;

    & .main {
        height: 100%;
        width: 100%;
        min-height: 100vh;

        & canvas {
            height: 100%;
        }
    }
`;

export default () => {
    const [vantaEffect, setVantaEffect] = useState(0);
    const vantaRef = useRef(null);

    useEffect(() => {
        if (!vantaEffect) {

            setVantaEffect(TOPOLOGY({
                el: vantaRef.current,
                THREE
            }))
        }

        return () => {
            if (vantaEffect) vantaEffect.destroy()
        }
    }, [vantaEffect])

    return (
        <div className={style}>
            <main className="main" ref={vantaRef}>

            </main>
        </div>
    )
};
```

```
import '../data/globals.css'
import { useEffect } from "react";

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    const threeScript = document.createElement("script");
    threeScript.setAttribute("id", "threeScript");
    threeScript.setAttribute(
      "src",
      "https://cdnjs.cloudflare.com/ajax/libs/three.js/r119/three.min.js"
    );
    document.getElementsByTagName("head")[0].appendChild(threeScript);
    return () => {
      if (threeScript) {
        threeScript.remove();
      }
    };
  }, []);
  return <Component {...pageProps} />;
}

export default MyApp;
```

**Comment by zhengAnBin** [comment]
me too

**Comment by JasonLandbridge** [comment]
@tengbao, is this something that can be fixed? If you need help than please reach out

**Comment by tengbao** [comment]
Thanks everyone! I've updated all the Geometries now.

**Comment by tengbao** [comment]
also @ncn-ends , the topology effect uses p5.js, not three.js -- maybe that's causing the problem? Try including p5.js
