### ISSUE TITLE
Birds not showing when scrolling

### ISSUE THREAD

**Issue by sidharthmenon** [tengbao/vanta#11]
three.r92.min.js:35 THREE.WebGLRenderer: OES_texture_float_linear extension not supported.

when scrolling animation stops and console has this error message. even when using demo https://www.vantajs.com/?effect=birds

**Comment by tengbao** [comment]
Ah, some GPU operations are not supported on certain devices (https://github.com/mrdoob/three.js/issues/13164). I will need to develop a fallback for mobile. Thanks for bringing this to my attention

**Comment by tengbao** [comment]
A mobile fallback has been implemented for birds. I can't repro the issue, so I'll consider this resolved.
