### ISSUE TITLE
Squarespace compatibility?

### ISSUE THREAD

**Issue by christophermoyer** [tengbao/vanta#110]
Hey, all — such a great little package. Is it fundamentally unusable for Squarespace, though, does anyone know? After trying everything and combing SquareSpace's support forums, I'm starting to think I'm missing something about the script's construction that means it will never work with SS. Can anyone say for sure? Thanks for any help you can provide.

**Comment by tengbao** [comment]
Vanta works with any platform that lets you add javascript. Squarespace does allow this: https://support.squarespace.com/hc/en-us/articles/205815928-Adding-custom-code-to-your-site

You'll need to get an element selector, and pass it to the vanta initializer function.

**Comment by christophermoyer** [comment]
Thanks! I did get it working eventually back when I asked. It works great. Thanks for your great work.

Christopher Moyer
***@***.*** ***@***.***>
PGP: keybase.io/moyer <http://keybase.io/moyer>
Twitter <https://twitter.com/iamchrismoyer> | Instagram <https://www.instagram.com/bareyourteeth/>
