### ISSUE TITLE
Vanta abandoned?

### ISSUE THREAD

**Issue by JasonLandbridge** [tengbao/vanta#114]
Hey @tengbao, 

Is this project still maintained or are you looking for someone to take over?

**Comment by i-am-the-slime** [comment]
I'd say that's a no.

**Comment by tengbao** [comment]
Sorry for delays! Just put in some updates, and will continue to review issues

**Comment by JasonLandbridge** [comment]
Awesome, good to have you back! Thanks for all the work you do!
