### ISSUE TITLE
Error when using Vanta with React please help

### ISSUE THREAD

**Issue by NimishKashyap** [tengbao/vanta#116]
×
TypeError: Cannot read properties of undefined (reading 'prototype')

Getting this error.
![image](https://user-images.githubusercontent.com/74850106/133937575-7a969f10-4bf3-425e-9c67-6cdce885ef8e.png)
I am very new to Vanta and I need to implement this using React only

Please help!

**Comment by NimishKashyap** [comment]
![image](https://user-images.githubusercontent.com/74850106/133937594-5cab954a-dfa2-4593-8940-8dd8239d7549.png)
This is my index.html

![image](https://user-images.githubusercontent.com/74850106/133937606-e5c7c813-aee6-4745-a050-61e9287ff0c2.png)

![image](https://user-images.githubusercontent.com/74850106/133937615-e0930b30-4188-4cfa-b3b8-5775f1a5ee01.png)

**Comment by koji** [comment]
@NimishKashyap 
Did you solve the issue?
If not,  this might be useful.

Here is my CodeSandbox
https://codesandbox.io/s/jolly-morning-m9f3p?file=/src/components/MyComponent.js

**Comment by chazkondo** [comment]
Changing my three version did the trick for me.

"three": "0.121.0"

@koji 
Thanks for sharing your fix

**Comment by i-am-the-slime** [comment]
Yes, I got the same 💩 , how do you do this with a modern version of three?

**Comment by i-am-the-slime** [comment]
Three 0.121.0 has a Denial of Service vuln.

**Comment by elrumordelaluz** [comment]
I am using `"three": "0.124.0"`

**Comment by tengbao** [comment]
I've updated the library so it now works three r134. See the react examples and fiddle links in the readme https://github.com/tengbao/vanta/

Closing this issue now.
