### ISSUE TITLE
Force re-draw

### ISSUE THREAD

**Issue by nazariydolfin** [tengbao/vanta#12]
Is there a way to force re-draw? When I resize the window the effect breaks and it says:

```
vanta.topology.min.js:1 Uncaught TypeError: Cannot read property '7' of undefined
    at vanta.topology.min.js:1
    at t.draw (vanta.topology.min.js:1)
    at e.redraw (p5.min.js:8)
    at e.<anonymous> (p5.min.js:7)
```

The best that I can do is to draw the whole thing again once the window size is less than x px. That creates a new canvas object. Wonder if there is a better solution.

**Comment by nazariydolfin** [comment]
If you start from this smaller width initially and then resize to bigger and then to this smaller, then everything works fine!

**Comment by nazariydolfin** [comment]
Also, this width length at which everything breaks happens to be when flexbox starts wrapping the elements on the page so that they fit in nicely and are responsive.

**Comment by tengbao** [comment]
@nazariydolfin can you please send a link to the broken page? Or a fiddle? I'd like to see which kind of flexbox settings are breaking the effect.

Window resize works fine for me here: https://www.vantajs.com/?effect=topology

**Comment by tengbao** [comment]
Perhaps you mean if the container changes size, but the window doesn't. You can do that by writing: 

```
const effect = VANTA.WAVES({
  el: '#my-background',
})

// Later, when the container changes sizes and you want to force Vanta to redraw at the new canvas size
effect.resize()
```
