### ISSUE TITLE
0x prefix for colors

### ISSUE THREAD

**Issue by shinokada** [tengbao/vanta#122]
Are there any reasons not to use `#`?

For example, the color `#4ddede` won't work, but `0x4ddede`.

Normal color pickers use `#` rather than `0x`.

Is it possible to use `#`?

**Comment by koji** [comment]
How did you pass css color hex code?
vanta uses three and it allows us to use hex code.

Actually, vanta works with css color hex code.
https://codesandbox.io/s/jolly-morning-m9f3p?file=/src/components/MyComponent.js

**Comment by shinokada** [comment]
I tried it with hex, but it didn't work.
Your demo is not working either.

**Comment by koji** [comment]
really? the code works on my end 👇

![Screen Shot 2022-01-20 at 1 37 56 AM](https://user-images.githubusercontent.com/474225/150286532-4777d7dc-4694-4a24-87fa-0e82c1fad8cf.png)

**Comment by shinokada** [comment]
Mmmm, it was not working, but it works now. Thanks.

Now I found the problem.

I used without quotes.

```
color1: #4ddede,
color2: #d2c721,
```

It works with quotes:

```
color1: "#4ddede",
color2: "#d2c721",
```

Thanks.
