### ISSUE TITLE
vantajs.com ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by elrumordelaluz** [tengbao/vanta#123]
![Screenshot 2022-01-28 at 19 30 46](https://user-images.githubusercontent.com/784056/151602114-a767779f-30b0-4ded-a9ad-4eb6e6a7dbab.png)
![Screenshot 2022-01-28 at 19 31 41](https://user-images.githubusercontent.com/784056/151602180-36550296-3ba8-4d5e-8c64-4248712c04d9.png)

**Comment by alexmslv** [comment]
+1
![image](https://user-images.githubusercontent.com/86348836/151782561-802f810c-7b45-4a83-ad4e-6d43978bf27c.png)
![image2](https://user-images.githubusercontent.com/86348836/151782573-817719a4-1c57-4636-b856-8777ab0f0b98.png)

**Comment by wanacode** [comment]
Meanwhile you can use https://web.archive.org/web/20220124115705/https://www.vantajs.com/

**Comment by elrumordelaluz** [comment]
Seems that is solved now!
