### ISSUE TITLE
Problem to use vanta js in wordpress

### ISSUE THREAD

**Issue by winniejo** [tengbao/vanta#133]
Iam using wordpress with elementor (2022) basic (not pro) and having a hard time to get it to work . Do you have a description how to solve this ? since there are descriptions for basic use, react, vue2, NPM etc. The users of wordpress is far beyond the general JS  react, vue2, NPM etc framework users .

winn

**Comment by tengbao** [comment]
The "basic use" case should work just fine for Wordpress. You'll need to add some code to the <head> tag. Maybe these tutorials can help: https://www.wpbeginner.com/wp-tutorials/how-to-easily-add-javascript-in-wordpress-pages-or-posts/ ,
https://themeisle.com/blog/wordpress-custom-javascript/#plugin

You'll need to select the target element somehow -- that depends on whatever theme you're using, but they should all come with some classname or ID selector you can use.
