### ISSUE TITLE
Geometry error

### ISSUE THREAD

**Issue by pri-2022** [tengbao/vanta#134]
When I visited the site using Edge and Chrome browsers, the site reported an error:
     
       Uncaught TypeError: Cannot read properties of undefined (reading 'Geometry')

![image](https://user-images.githubusercontent.com/101853128/165659984-b2e33262-95fd-44f9-9159-0987a8391538.png)

![image](https://user-images.githubusercontent.com/101853128/165660065-103f6489-0aef-4f50-988d-8840ae751c2a.png)

**Comment by mrLuisFer** [comment]
Same problem, even installing THREE as a dependency and using the official CDN

**Comment by tanabut-chan** [comment]
Same here.

**Comment by leateng** [comment]
same error

**Comment by 0ptim** [comment]
Same

**Comment by tengbao** [comment]
The dependencies from the cloudflare cdn didn't load for you, seems like a network issue. The demo site works OK for me, closing this issue for now.
