### ISSUE TITLE
WAVES speed differs across devices

### ISSUE THREAD

**Issue by baobabKoodaa** [tengbao/vanta#138]
Hi! First of all, I love the animations. Especially WAVES and HALO, man they look really nice.

I just took WAVES into use on my personal website, and after testing it with different devices I noticed that the speed is drastically different depending on device:

- I developed this on my laptop and I set the waves speed to a relaxing pace
- On my desktop computer the waves go really fast (about 3x what they go on my laptop) and it feels really restless
- On my mobile phone the waves go really slow (maybe 1/5 what they go on my laptop, 1/15 what they go on my desktop)

I understand that different devices have different performance, but that should only affect the framerate, not the speed at which animations progress.

**Comment by tengbao** [comment]
thanks for reporting this bug! fixed in https://github.com/tengbao/vanta/commit/ff5cd8a1839794800c678a958c249a50dd1f5a18 , will be released as an update to npm soon

**Comment by baobabKoodaa** [comment]
Thank you, much appreciated!
