### ISSUE TITLE
TypeError: Cannot read property 'BIRDS' of undefined (React/Gatsby.js)

### ISSUE THREAD

**Issue by Saayaman** [tengbao/vanta#14]
Hi @tengbao ! thanks for the awesome job!
I was trying to implement this in react but it wasn't working for some reason.

Steps to reproduce the problem...
### 3. import it in a react component. 
```
class BirdsAnimation extends React.Component {
  constructor(props) {
    super(props);
    this.yourElement = React.createRef();
  }

  componentDidMount() {
    const yourElement = this.yourElement.current;

    if (typeof window !== undefined) {
      this.effect = window.VANTA.BIRDS({
        el: yourElement,
        color1: 0xff,
        color2: 0xffffff,
        colorMode: 'variance',
        wingSpan: 40.0,
        speedLimit: 8.0,
        alignment: 1.0,
        cohesion: 48.0,
        quantity: 4.0,
        backgroundAlpha: 0.0,
      });
    }
  }

  componentWillUnmount() {
    if (this.effect) this.effect.destroy();
  }
  render() {
    return <div className="BirdsAnimation" ref={this.yourElement} />;
  }
}

export default BirdsAnimation;
```
### 4. Error message: 
```
Uncaught TypeError: Cannot read property 'BIRDS' of undefined
```

### NOTE: It DOES works when I use the `CDN` url in this issue #3, but I want to read the file locally.

**Comment by danielsinai** [comment]
Hey,
   This happens to me as well if you found a solution could you let me know?

**Comment by beeinger** [comment]
I am developing on nextjs and encountered same problem, i have solved it 
The answer is to expose this file (vanta.birds.min.js) on static route from your code and access it like that:

<script src="/static/scripts/vanta.net.min.js" />
^this is how my route looks like

Everything working fine :)

**Comment by bchachaj** [comment]
I had the same issue, using Gatbsy too. Like @beeinger , ended having to add a 'static' folder at the root of the project. So if my static folder has a directory called 'js', I can then reference from the html.js like this:         
<script src="/js/three.min.js"></script>
<script src="/js/vanta.min.js"></script>

**Comment by tengbao** [comment]
@Saayaman 

I've fixed this issue. Now you can import `vanta.xxxxx.min.js` either as a static file in a <script> tag, or using `import xxxxx from 'vanta.xxxxx.min.js'`. 

Please check the "Usage In React" section of the readme for more info: https://github.com/tengbao/vanta
