### ISSUE TITLE
VantaJS bird effect visible on mobile-web browsers?

### ISSUE THREAD

**Issue by elolelo** [tengbao/vanta#15]
Is the current release of vantaJS (particularly the bird effect) supposed to be compatible with any web browser on mobile? 

I used for my website but it is not visible on most mobile browsers that I tried in on.

**Comment by tengbao** [comment]
The current implementation doesn't work on mobile. I'll make a mobile-friendly version soon!

**Comment by tengbao** [comment]
Birds now works on mobile, check it out: https://www.vantajs.com
https://github.com/tengbao/vanta/commit/10e12d25f992e94451dd39942b8e89da2a839ff3

**Comment by elolelo** [comment]
> @elolelo Birds now works on mobile, check it out: https://www.vantajs.com
> [10e12d2](https://github.com/tengbao/vanta/commit/10e12d25f992e94451dd39942b8e89da2a839ff3)

Good work - thanks! for updating me. How are the gestures, are they working on your mobile browser? are you able to affect the direction of the birds on mobile just like you can on web?

**Comment by tengbao** [comment]
@elolelo I've updated the code to allow mobile touches! https://github.com/tengbao/vanta/commit/bcb9733fdc4096c99b665f4267314391ec2b4c72

Please update using the newest version of the file.
