### ISSUE TITLE
vanta.js and barba.js v1 not working properly

### ISSUE THREAD

**Issue by kumaaa** [tengbao/vanta#17]
Hello,

i am using barba.js v1 on my website and i would like to use vanta.waves as a header background on my subpages.

unfortunately the script wont initialize after a page transition,
only if I refresh the page (ctrl + r) then the canvas is rendered

how can i solve this?

**Comment by tengbao** [comment]
Check the "Usage In React" section of the Readme (https://github.com/tengbao/vanta/) -- you'll probably need to do a manual cleanup/reinit on page transition.

**Comment by tengbao** [comment]
You'll probably need to manually cleanup the old effect and re-initialize the new effect, on page transition.

Check the "Usage In React" section of the Readme (https://github.com/tengbao/vanta/) for a simple example of cleanup/reinit: `effect.destroy()` to cleanup, `effect = window.VANTA.BIRDS({el: "#my-element"})` to reinit
