### ISSUE TITLE
How do I add it to Wordpress?

### ISSUE THREAD

**Issue by ericlesmths** [tengbao/vanta#19]
I'm very new to javascript and would like to use Topology as a background on a Wordpress website. I'm using Divi and tried to add the code with the cdn, but it didn't work. I have no idea what I'm doing.

Where do I start?

**Comment by heliabisadi** [comment]
Hi
I have the same issue. How did it work for you?
How can I add vanta birds to my wordpress website?

**Comment by tengbao** [comment]
You'll need to add the two required scripts (vanta.birds.min.js and three.min.js) into the <head> tag, then initialize the effect by targeting an element on the page. Check the jsfiddle for a simple example: https://jsfiddle.net/xb74q5h1/

**Comment by annahda** [comment]
@tengbao  hi, I have no coding experience but I want to add vanta fog to my WordPress website. Can you give me a step by step guide on how to do that?
