### ISSUE TITLE
Add vanta birds to wordpress

### ISSUE THREAD

**Issue by heliabisadi** [tengbao/vanta#20]
Hi
How can I add Vanta birds to my wordpress website?Do I need any plugins?

**Comment by tengbao** [comment]
You'll need to include `three.min.js` (find it [here](https://github.com/tengbao/vanta/tree/master/vendor)) and `vanta.birds.min.js` (find it [here](https://github.com/tengbao/vanta/tree/master/dist)). Then, just follow the example in the readme.

**Comment by tengbao** [comment]
You'll need to include `three.min.js` ([find it here](https://github.com/tengbao/vanta/tree/master/vendor)) and `vanta.birds.min.js` ([find it here](https://github.com/tengbao/vanta/tree/master/dist)). Then, just follow the example in the readme. 😄

**Comment by annahda** [comment]
I don't have any coding experiance, can you tell me how to include .js files in wordpress.
