### ISSUE TITLE
Mix Three.js with vanta into a single small file

### ISSUE THREAD

**Issue by EPurpl3** [tengbao/vanta#21]
Not a issue, is more a idea. It could be great if you could remove all the unused parts from Three.js and keep only the required parts so it will result a mix of Three.js and Vanta.js that will be very compact.

Very good plugin, BTW. Great job.

Thank you.

**Comment by tengbao** [comment]
It's a good idea to reduce filesize, though each effect would need its own build. If anyone wants to give this a go, I'm happy to review merge requests -- but I'll close this for now.
