### ISSUE TITLE
Background freeze on scroll

### ISSUE THREAD

**Issue by StarfallProjects** [tengbao/vanta#22]
Hi! I'm using the NET animation for my website background and have a small problem - any advice/fix greatly appreciated.

On a [page with a long list of content](https://www.starfallprojects.co.uk/blog/), I initially had the problem of the animation being fixed height, so when I scrolled down the animation scrolled off and I just had my page background color. I fixed this by doing:

```
.vanta-canvas {
    position: fixed !important;
}
```
(Not best practice? I'd welcome advice on an alternative)

This looks ok, but when I scroll down the animation stops animating/freezes in place. There are no error messages. It occurs in Chrome and Firefox latest, and in Edge (all on desktop)

Is this an issue with Vanta, with three.js, or with my solution to the fixed height on .vanta-canvas?

**Comment by tengbao** [comment]
It seems attaching the effect directly to <body> messes up the calculations a bit. I'll find a solution.

In the meantime, you should add a container element as a child of <body> and attach the Vanta effect to that container, instead of directly to body. Then style the container so it's the right size and `position: fixed`.

**Comment by StarfallProjects** [comment]
Thanks for the swift response. Container element/alternative element caused an issue in Edge (which I can't fathom - it scrolled off despite being fixed). Will leave as is for now and watch for any solution :-)

**Comment by tengbao** [comment]
@StarfallProjects I just added a `forceAnimate` option. If you set that to `true`, it'll always animate.

https://github.com/tengbao/vanta/commit/4d7f1d5330df5e521346773754bdc9022923ac4e
