### ISSUE TITLE
VANTA is not defined...???

### ISSUE THREAD

**Issue by am8525** [tengbao/vanta#24]
Just going for a simple background animation and running into issues that seem to be located in the Vanta source code.

Here is my code:
```
import React from 'react';
import { createStyles, withStyles } from '@material-ui/core/styles';
import * as THREE from '../lib/vanta-js/vendor/three.r92.min.js';
import WAVES from '../lib/vanta-js/dist/vanta.waves.min.js';

const styles = () => createStyles({
	backRoot: {
		zIndex: '-1',
		width: '100%',
		height: '100%'
	}
})

class Background extends React.Component {

	constructor(props) {
		super(props);
		this.myRef = React.createRef();
	}

	render() {
		const { classes } = this.props;

		return (<div className={classes.backRoot}
					 ref={this.myRef}/>)
	}

	componentDidMount() {
		this.effect = WAVES({
			el: this.myRef.current
		});
	}

	componentWillUnmount() {
		if (this.effect) this.effect.destroy();
	}
}

export default withStyles(styles)(Background);
```

And here is the stack trace:
```
./src/lib/vanta-js/dist/vanta.waves.min.js
  Line 1:      Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:    'define' is not defined                                                no-undef
  Line 1:    'define' is not defined                                                no-undef
  Line 1:    Unexpected use of 'self'                                               no-restricted-globals
  Line 1:    Unexpected use of 'self'                                               no-restricted-globals
  Line 1:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  'VANTA' is not defined                                                 no-undef
```

**Comment by tengbao** [comment]
Thanks for the bug report! Fixed in https://github.com/tengbao/vanta/commit/3020eba2b9ee59d57f19d060d7b7c9c99ea069e6

**Comment by MikeSilverstone** [comment]
I believe this needs reopening.

**Comment by cjnunez** [comment]
I am also still running into this issue!

**Comment by shubhq2** [comment]
I have also same issue with vanta.birds.min.js

`./src/Venta/vanta.birds.min.js
  Line 1:1:      Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:112:    'define' is not defined                                                no-undef
  Line 1:123:    'define' is not defined                                                no-undef
  Line 1:226:    Unexpected use of 'self'                                               no-restricted-globals
  Line 1:231:    Unexpected use of 'self'                                               no-restricted-globals
  Line 1:530:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:1416:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:2537:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:2703:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:3455:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:3604:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:4048:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:4340:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:4486:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:5057:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:5362:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:5503:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:5712:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:5979:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:7561:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:7775:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:8217:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:8272:   'THREE' is not defined                                                 no-undef
  Line 1:8290:   'THREE' is not defined                                                 no-undef
  Line 1:8507:   'THREE' is not defined                                                 no-undef
  Line 1:8522:   'THREE' is not defined                                                 no-undef
  Line 1:8670:   'THREE' is not defined                                                 no-undef
  Line 1:8815:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:8998:   'THREE' is not defined                                                 no-undef
  Line 1:9028:   'THREE' is not defined                                                 no-undef
  Line 1:9415:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:10030:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:10874:  'THREE' is not defined                                                 no-undef
  Line 1:10905:  'THREE' is not defined                                                 no-undef
  Line 1:10936:  'THREE' is not defined                                                 no-undef
  Line 1:10961:  'THREE' is not defined                                                 no-undef
  Line 1:10985:  'THREE' is not defined                                                 no-undef
  Line 1:11061:  'THREE' is not defined                                                 no-undef
  Line 1:11131:  'THREE' is not defined                                                 no-undef
  Line 1:11151:  'THREE' is not defined                                                 no-undef
  Line 1:11220:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:11270:  'THREE' is not defined                                                 no-undef
  Line 1:11294:  'THREE' is not defined                                                 no-undef
  Line 1:11311:  'THREE' is not defined                                                 no-undef
  Line 1:11388:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:11487:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:11803:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:12071:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:12207:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:12241:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:12828:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:13004:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:13120:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:13589:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:13871:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:14177:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:14276:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:14510:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:20913:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:21133:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:21205:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:21232:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:21523:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:21797:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:22030:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:22539:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:22698:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:24928:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:25157:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:25393:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:25836:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:25923:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:26195:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:26501:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:26626:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:27275:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:27855:  Expected an assignment or function call and instead saw an expression  no-unused-expressions`

**Comment by blyndusk** [comment]
@shubhq2 use `/* eslint-disable */` at the top of `vanta.birds.min.js` to avoid eslint warnings/errors !

**Comment by ElPoul3to** [comment]
Hey, I have also VANTA is not defined but I use vanta in static:
`---
import Section from "../components/Section.astro";
---

<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" type="image/svg+xml" href="/favicon.svg" />
		<meta name="viewport" content="width=device-width" />
		<meta name="generator" content={Astro.generator} />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link
			href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
			rel="stylesheet"
		/>
		<link
			href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
			rel="stylesheet"
		/>
		<link rel="stylesheet" href="style.css" />

		<title>Imagine</title>

		<style type="text/css">
			* {
				margin: 0;
				padding: 0;
				box-sizing: border-box;
			}
			body {
				overflow: hidden;
			}
			#vantaJS {
				width: 100%;
				height: 100%;
			}
		</style>
	</head>

	<body>
		<div id="vantaJS"></div>
		<script
			src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r134/three.min.js"
		></script>
		<script
			src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.birds.min.js"
		></script>
		<script>
			VANTA.BIRDS({
				el: "#vantaJS",
				mouseControls: true,
				touchControls: true,
				gyroControls: false,
				minHeight: 200.0,
				minWidth: 200.0,
				scale: 1.0,
				scaleMobile: 1.0,
				color1: 0x6fa7e9,
				color2: 0x71caf0,
			});
		</script>

		<div class="mt-5 p-20 rounded">
			<Section nom_service="Nom" />
			<Section nom_service="Nom" />
		</div>
	</body>
</html>
`
I think it comes from <script src="https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.birds.min.js"></script> but I am not sure. Do you have any idea ?
