### ISSUE TITLE
VueJS example

### ISSUE THREAD

**Issue by schmidfelix** [tengbao/vanta#25]
Hi, 

before I start, I already saw #18 .

It would be very nice if you cold post an example for vueJS, because there is no nuxt.config.js like in VueJS with Nuxt and I'm getting errors with every try. 

Best regards and a nice day

**Comment by Olli2** [comment]
Not sure if this is the most efficient way of doing this but here is one resolution:

**Comment by cp-ugorji** [comment]
# Working with Vanta.js in Vue
* add below script tag to the head of index.html file in public folder
```
<script src="https://cdn.jsdelivr.net/gh/tengbao/vanta/vendor/three.r92.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/tengbao/vanta/dist/vanta.globe.min.js"></script>
```
* In the component or .vue file where you want to use it, load it on the mounted hook.
```
mounted() {
    window.VANTA.GLOBE({
      el: "#app"
    });
}
```

**Comment by anthonyboutinov** [comment]
Hello! I used it like that:

- Install with npm (`npm i vanta`, `npm i three`) and import in .vue file for the page where it's used:

```
import * as THREE from 'three'
import NET from 'vanta/dist/vanta.net.min'
```

- In the .vue file, attach an instance of Vanta to the component:

```
mounted() {
  this.vantaEffect = NET({
    el: "#home-jumbotron",
    // ...
  });
}
```

- I'm trying to delete Vanta instance on `beforeDestroyed()` or `destroyed()`, but nothing happens. The canvas is still present in the Developer Web Inspector. So visiting the page where Vanta is used creates multiple instances of canvas which negatively affects the performance of the website.

```
beforeDestroy() {
  this.vantaEffect.destroy();    // <-- doesn't seem to work for me
}
```

Am I doing something wrong?

**Comment by lukeshiels** [comment]
In case someone gets a 'Group' error or similar, here's how I got it to work:
1. Import as per other commenters:
```
import Vanta from 'vanta/dist/vanta.net.min';
import * as THREE from 'three';
```
2. Add the initialisation as usual __but pass the THREE instance to the initialisation__:
```
mounted() {
  this.vantaEffect = Vanta({
    el: "#home-jumbotron",
    VANTA,
  });
}

**Comment by mnlema** [comment]
@anthonyboutinov Hello, I need to finish the vanta effect when I change the page, how can I do it?
Did you solve?

**Comment by tengbao** [comment]
@mnlema Please see the vue example I added to the readme! It shows how to destroy the effect.
