### ISSUE TITLE
Updating some options after init

### ISSUE THREAD

**Issue by interactivist** [tengbao/vanta#26]
I have initialized the effect by following code and it works. But how ist it possible to update some options later - for example the hightlightColor - without restarting the complete animation?

VANTA.FOG({
  el: "#example",
  highlightColor: 0x57230e,
  midtoneColor: 0x461a08,
  lowlightColor: 0x2f140b,
  baseColor: 0x0,
  blurFactor: 0.77,
  speed: 3.60,
  zoom: 2.50
})

**Comment by tengbao** [comment]
Currently, you can write:

```
// Init
var effect = VANTA.FOG({
  el: "#example",
  highlightColor: 0x57230e,
  midtoneColor: 0x461a08,
  lowlightColor: 0x2f140b,
  baseColor: 0x0,
  blurFactor: 0.77,
  speed: 3.60,
  zoom: 2.50
})
// Later, when you want to update:
effect.options.midtoneColor = 0x00ff00;
effect.updateUniforms();
```

**Comment by interactivist** [comment]
Thank you. The code I have received via email is working but the code differs from the answer in the forum - it is incomplete ?

// Init
var effect = VANTA.FOG({
  el: "#example",
  highlightColor: 0x57230e,
  midtoneColor: 0x461a08,
  lowlightColor: 0x2f140b,
  baseColor: 0x0,
  blurFactor: 0.77,
  speed: 3.60,
  zoom: 2.50
})
// Later, when you want to update:
effect.options.midtoneColor = 0x00ff00;
effect.updateUniforms();
