### ISSUE TITLE
Can't get to initialize

### ISSUE THREAD

**Issue by RichardTPowell** [tengbao/vanta#27]
I can't get this to work on my server or my local host. I can preview it with Brackets, but only when I copy and paste in...
    <script>
        VANTA.FOG('#fog')
    </script>

Then the live view updates. 
This does not happen when live viewing other WebGL projects.

**Comment by tengbao** [comment]
@RichardTPowell Is there an error in console?

**Comment by 11reed** [comment]
Having this same issue. Any chance you solved this problem?

**Comment by tengbao** [comment]
@RichardTPowell @11reed Do you have specific steps to reproduce the error? Which local server are you using? Are you using any frameworks (react, vue, etc)?

**Comment by RichardTPowell** [comment]
Hi @tengbao Thank you for your diligence with this, I ended up using a pure CSS-based solution for my project, I would like to use these for future projects, but I am very new to JS in particular. I am about to go out of the country for a while, I'll give as detailed as I can snapshot when I return mid Feb, thank you.

**Comment by tengbao** [comment]
Closing this due to lack of specificity
