### ISSUE TITLE
Add React.js working example in the repo

### ISSUE THREAD

**Issue by chandan-reddy-k** [tengbao/vanta#29]
I love the concept of Vanta.js offering great customizability to three.js. Unfortunately, I was not able to get this working and implement in my create-react-app. I followed README for implementation in react (both hooks and classes didn't work) . I keep getting 'define' is not defined and other compilation errors. I also tried using script tags but nothing worked.  It would be great if you can add a complete  working example of react + vanta in the repo.

**Comment by tengbao** [comment]
Please see https://github.com/tengbao/vanta/issues/30 for a working example with `create-react-app`
