### ISSUE TITLE
[Dots] How to remove/hide big bubble on the middle? 

### ISSUE THREAD

**Issue by StevRoger** [tengbao/vanta#36]
I am using Vata JS Dots style and I want to remove/hide the big bubble spinning in the middle. How Can I do that?

**Comment by Mish325** [comment]
I'm having the same problem. Want to remove or hide that element. Please help with that @tengbao  :)

**Comment by tengbao** [comment]
@StevRoger @Mish325 You can now add `showLines: false` in the options
Done in https://github.com/tengbao/vanta/commit/a4c658ac279e63ae006c89acbec825a5ccc36222
