### ISSUE TITLE
Is there a way to modulate an option of a Vanta?

### ISSUE THREAD

**Issue by wrightwriter** [tengbao/vanta#4]
I want to change the zoom smoothly like in the Vanta.waves example. Sadly, once I change the property, the shader restarts. Is it possible to do it ?

**Comment by tengbao** [comment]
Currently not possible through the Vanta API, but this is a good suggestion for a future version! 

In the meantime (with some effort), you could take the Waves source code and modulate it however you want.

**Comment by tengbao** [comment]
Yes, like this:

```
// init
var effect = VANTA.WAVES('#my-background')

// after some time:
effect.options.zoom = 0.5;
effect.triggerMouseMove(0,0)
```

**Comment by tengbao** [comment]
@wrightwriter Yes, like this:

```
// init
var effect = VANTA.WAVES('#my-background')

// after some time:
effect.options.zoom = 0.5;
effect.triggerMouseMove(0,0)
```
