### ISSUE TITLE
Angular integration

### ISSUE THREAD

**Issue by dellMarco** [tengbao/vanta#40]
Hi there, 

I tried to use BIRDS in an Angular for hours, but I just can't make it work. Is it even possible? If so, what are the steps?

Regards Marco

**Comment by alexandru-balan** [comment]
I use NET with Angular 8 and 9. You just load the **birds.min.js** in your case in the **angular.json** file like this:
*(Taken from my project)*
```json  
"scripts": [
              "./node_modules/uikit/dist/js/uikit.min.js",
              "./node_modules/uikit/dist/js/uikit-icons.min.js",
              "./node_modules/three/build/three.min.js",                <---- THREE GOES HERE
              "./src/app/Modules/landing/features/vanta.net.min.js"     <---- HERE
           ] 
```
You will also need to load THREE.JS which I have installed through yarn. You can install it with yarn, npm or download it from their github page.

For setting vanta up, I went into my component TS file and did this:
```js
ngOnInit() {
    this.effect = VANTA.NET({
      el: "#net-background",
      color: 0xca6c56,
      backgroundColor: 0x342071,
      points: 10.00,
      maxDistance: 15.00,
      spacing: 20.00
  })
  }
```

**Comment by tengbao** [comment]
Thanks for the solution @alexandru-balan . If you can provide a fiddle, I can add it to the readme. Closing this issue now
