### ISSUE TITLE
I read through your docs but cannot integrate into this Gatsby boilerplate

### ISSUE THREAD

**Issue by FarhadG** [tengbao/vanta#41]
I tried every variation in your docs but cannot get this to work with this theme: https://github.com/narative/gatsby-theme-novela

Any help would be appreciated.

**Comment by pranaybaldev** [comment]
Hi @FarhadG. [This](https://github.com/luminositylab/luminosity-frontend) might help you. Cheers.

**Comment by tengbao** [comment]
@FarhadG Gatsby is a React site generator, so you can define your own React components. The vanta readme guide should work fine. This might also help: https://www.gatsbyjs.org/docs/building-with-components/

Closing this issue.
