### ISSUE TITLE
The 3D Animation is stopped when scrolling down the page.

### ISSUE THREAD

**Issue by LovageIO** [tengbao/vanta#45]
Hi

I have completely written the code as same as the example, but the 3D animation is stopped once I scroll down the page. You can check the demo here: https://lovage.io/3d  and my codes below:

<!DOCTYPE html>
<html lang="en-US">
  <head>
  	<meta charset="UTF-8">
	<title>3D</title>
	<script type="text/javascript" src="./js/three.r92.min.js"></script>
	<script type="text/javascript" src="./js/vanta.wave.min.js"></script>
  </head>

  <body>
	<div id="layer"></div>
	<div style="height:3000px;"></div>

	<script>
		VANTA.WAVES({
		      el: "#layer",
		});
	</script>	
  </body>
  
</html>

However, the official demos works fine on my browser. Could you give me any tips?

Thanks

**Comment by LovageIO** [comment]
Sorry, paste the code again

``
<!DOCTYPE html>
<html lang="en-US">
  <head>
  	<meta charset="UTF-8">
	<title>3D</title>
	<script type="text/javascript" src="./js/three.r92.min.js"></script>
	<script type="text/javascript" src="./js/vanta.wave.min.js"></script>
  </head>

  <body>
	<div id="layer"></div>
	<div style="height:3000px;"></div>

	<script>
		VANTA.WAVES({
		      el: "#layer",
		});
	</script>	
  </body>
  
</html>
``

**Comment by LovageIO** [comment]
```
<!DOCTYPE html>
<html lang="en-US">
  <head>
  	<meta charset="UTF-8">
	<title>3D</title>
	<script type="text/javascript" src="./js/three.r92.min.js"></script>
	<script type="text/javascript" src="./js/vanta.wave.min.js"></script>
  </head>

  <body>
	<div id="layer"></div>
	<div style="height:3000px;"></div>

	<script>
		VANTA.WAVES({
		      el: "#layer",
		});
	</script>	
  </body>
  
</html>
```

**Comment by pranaybaldev** [comment]
Use section instead of div

**Comment by LovageIO** [comment]
I tried, but still no luck.

**Comment by tengbao** [comment]
Ah I see the problem. This issue will be fixed if you set a height or add some inner content on your `<div id="layer"></div>` element! Meanwhile, I'll fix the code.

**Comment by tengbao** [comment]
@LovageIO Ah I see the problem. This issue will be fixed if you set a height or add some inner content on your `<div id="layer"></div>` element! Meanwhile, I'll fix the code.

**Comment by tengbao** [comment]
@LovageIO The above solution will work for the old code, or you can update to the new version, which makes the height/width logic clearer. Either way, you'll probably want to explicitly set a height on the `#layer` element. 

Fixed in https://github.com/tengbao/vanta/commit/b769f2eae8334bee03c6feebd49ecdacad0ae55b
