### ISSUE TITLE
Did css params changed after update?

### ISSUE THREAD

**Issue by WildHunt** [tengbao/vanta#47]
I'm using Vanta js as a background full-sized image, but few days ago it's changed.
You can look, what I mean here: <code> http://52.14.177.85/</code> 
I didn't change html or css code, so I belive it's because of vanta update. I don't understand, why it's no longer works as usual

**Comment by WildHunt** [comment]
If I'm changing high, in my case, I have it blur and low quality also width is reducing.

**Comment by tengbao** [comment]
@WildHunt Please see https://github.com/tengbao/vanta/issues/46
