### ISSUE TITLE
Vanta should check if window.THREE is ready

### ISSUE THREAD

**Issue by StarfallProjects** [tengbao/vanta#48]
I'm hitting an error when I load three.r95.min.js and vanta.net.min.js asynchronously (which is necessary to avoid slow page loads) Admittedly only hitting it in Firefox, which is weird. But . . . 

`[VANTA]  No THREE defined on window`

It looks like vanta.net.js does the following without checking if win.THREE is defined/loaded:

`let THREE = win && window.THREE`

My solution would be the following, but I am not a JS dev and there may well be a more elegant way, hence submitting an issue rather than a PR:

```
var THREE;
let timer = setInterval(function(){
  if(window.THREE) {
    clearInterval(timer);
    THREE = win && window.THREE;
  }
},500);
```

**Comment by StarfallProjects** [comment]
To add -  for now I have worked around this with the following:

This in my `<head>`:
```
    <script>
    (function() {
        let scriptTimer = setInterval(function() {
            if(window.THREE) {
                clearInterval(scriptTimer);
                var fileref=document.createElement('script');
                fileref.setAttribute("type","text/javascript");
                fileref.setAttribute("method", "async");
                fileref.setAttribute("src", "{{ 'assets/js/vanta.net.min.js' | url }}");
                document.getElementsByTagName("head")[0].appendChild(fileref);
            }
        }, 500);
    })();
    </script>
```

And similarly a `setInterval` and check for `window.VANTA` before setting my options with `VANTA.NET`

**Comment by tengbao** [comment]
The error `[VANTA] No THREE defined on window` is only triggered when you call the Vanta init function (`VANTA.BIRDS(...)`). It's fine to load both vanta.js and three.js asynchronously, then initialize after both are loaded. 

Waiting for three.js is not the responsibility of this library. You can use promises to do that, e.g. https://codereview.stackexchange.com/questions/45541/wait-until-all-files-are-loaded-asynchronously-then-run-code.

**Comment by StarfallProjects** [comment]
I had tried this initially (check for window.VANTA and window.THREE before initialising VANTA. Bu this error: `[VANTA] No THREE defined on window` was thrown before any of my code ran. It was being thrown by the VANTA script itself - as far as I can tell, as soon as it loaded it ran.

**Comment by tengbao** [comment]
@StarfallProjects As far as I can tell, just loading the Vanta script (without the three.js script) should not cause any error. See here: https://jsfiddle.net/n6csdmpx/

Can you post a fiddle that shows the error on load?

**Comment by StarfallProjects** [comment]
@tengbao ok this is becoming a weird one. The JS Fiddle worked fine. I went back and tried on my site, and:
- worked fine in Chrome
- errors in Firefox (the fiddle worked fine here)
![image](https://user-images.githubusercontent.com/10284570/73606941-e7db8600-45a7-11ea-99b1-1c9297b0236e.png)
![image](https://user-images.githubusercontent.com/10284570/73606943-f033c100-45a7-11ea-91f6-dc81509c529a.png)

I am doing this in the `<head>`:
```
   <script src="{{ 'assets/js/three.r95.min.js' | url }}" async></script>
    <script src="{{ 'assets/js/vanta.net.min.js' | url }}" async></script>
```

And this in the script to initiate the animation (at the bottom of the page, just before `</body>`:
```
<script>  
(function() {
  var animTimer = setInterval(function(){
    if(window.VANTA && window.THREE) { 
      clearInterval(animTimer);
      VANTA.NET({
        el: "#animate-this",
        color: 0xf6ba8d,
        backgroundColor: 0x8daaf6,
        points: 20,
        maxDistance: isBigScreen(),
        spacing: 15,
        showDots: false,
        forceAnimate: true,
        THREE: THREE
      })    
    }
  }, 200);
})();

function isBigScreen() {
  if(screen.width > 1024) {
    return 30;
  }
  else {
    return 20;
  }
}
</script>
```

On the other hand, doing this works everywhere:
In `<head>`:
```
<script src="{{ 'assets/js/three.r95.min.js' | url }}" async></script>
<script>
(function() {
    let scriptTimer = setInterval(function() {
        if(window.THREE) {
            clearInterval(scriptTimer);
            var fileref=document.createElement('script');
            fileref.setAttribute("type","text/javascript");
            fileref.setAttribute("method", "async");
            fileref.setAttribute("src", "{{ 'assets/js/vanta.net.min.js' | url }}");
            document.getElementsByTagName("head")[0].appendChild(fileref);
        }
    }, 100);
 })();
</script>
```
And then in the animation initiation just checking for VANTA.

This is what made me think the vanta.net.min.js was running and looking for three.js before it should - because in Firefox it gives the errors in the screenshot, and because forcing the vanta.js to load after three.js solved it.
