### ISSUE TITLE
rendering differences in mobile

### ISSUE THREAD

**Issue by Doom666** [tengbao/vanta#49]
when using the net bg, in the desktop view is perfect, yet in the mobile view there is a million lines, I dont seem able to find a workaround, is like if the script understand that there is less distance between dots and then the same minimal distance value is applied.
does someone know how to deal with this?

**Comment by a-fuenzalida** [comment]
Same here, i tried to change the minHeight and minWidth but it affects the webpage size in general.

**Comment by tengbao** [comment]
Hmm, yea it does look too dense on mobile. A workaround for now: Set the maxDistance dynamically based on window size -- you can play around with the formula:

```
var effect = VANTA.NET('#element')
effect.setOptions({maxDistance: 20 * Math.min(1,Math.sqrt(window.innerWidth/500))})
```
