### ISSUE TITLE
How to use this in React.js

### ISSUE THREAD

**Issue by Chawki726** [tengbao/vanta#5]

**Comment by AlexandraKlein** [comment]
Include the library.
Define a ref in your constructor method: ` this.youElement = React.createRef();`
Attached ref to div `<div ref={this.youElement}>`
Add Vanta code to your componentDidMount:

```
 componentDidMount() {
    const youElement = this.youElement.current;
    VANTA.NET({
      el: youElement
    })
  }
```

**Comment by catedm** [comment]
I am vetting VANTA not defined in my react component when I try to use this method. Any suggestions? Thanks

**Comment by Nefraim** [comment]
Im getting the same error. Would anyone help to implement VANTA for React?
Thanks.

**Comment by tengbao** [comment]
It depends on how you're including the library in your project. If the script is properly included, `VANTA` will be defined on `window`, so you can just use `window.VANTA`

**Comment by tengbao** [comment]
@catedm @Nefraim It depends on how you're including the library in your project. If the script is properly included, `VANTA` will be defined on `window`, so you can just use `window.VANTA.NET({...})`

**Comment by tengbao** [comment]
@catedm @Nefraim If the script is properly included, `VANTA` will be defined on `window`, so you can just use `window.VANTA.NET({...})`

**Comment by tengbao** [comment]
@catedm @Nefraim If the script is properly included, `VANTA` will be defined on `window`, so you can just use `window.VANTA.NET({...})`.

You have to explicitly use `window.VANTA`, not just `VANTA`.

**Comment by catedm** [comment]
Thank you @tengbao, I was able to get it properly implemented using `window.VANTA`

**Comment by HrutvikPatel** [comment]
What are the steps to in React application? How do I import it I understand the part with window.VANTA.NET.. But I keep getting VANTA undefined no matter what I do. So clearly I am a noob and don't know how to use this lol. Please help :)

**Comment by Saayaman** [comment]
@HrutvikPatel it worked with CDN link
https://github.com/tengbao/vanta/issues/3
