### ISSUE TITLE
Site doesn't recognize Feb 29th as a date and all scripts are down

### ISSUE THREAD

**Issue by Marshmallows7920** [tengbao/vanta#53]
![image](https://user-images.githubusercontent.com/45214756/75613759-1bea8e00-5af7-11ea-96bb-fbde67eb0a27.png)

Update: SSL certificate expired

**Comment by IronVenom** [comment]
Yeah I want to use vanta in one of my projects, but I can't because I don't know how to set properties of the vanta.net.min.js file; like colors , etc.

**Comment by tengbao** [comment]
fixed! sorry about this
