### ISSUE TITLE
Zoom option only gets updated on mouse move

### ISSUE THREAD

**Issue by abdullah-K** [tengbao/vanta#59]
### Demo
[https://codepen.io/abdullah-k/pen/NWqeomv](https://codepen.io/abdullah-k/pen/NWqeomv)
### Issue
I am trying to update the zoom option in a `setTimeout` function using `effect.setOptions()`. The expected behavior is that the waves animation zooms out by itself after the specified time but, it only zooms out after there is some mouse movement over the canvas. Is there anything I can do to make it zoom out automatically?

_Issue occurs on Chrome, Firefox, and Safari_

**Comment by tengbao** [comment]
For now, please update to the newest version (https://cdn.jsdelivr.net/npm/vanta@0.5.16/dist/vanta.waves.min.js)

Then, you can just trigger the mouse manually like this:

```
document.addEventListener("DOMContentLoaded", function () {
  setTimeout(() => {
    console.log("update effect")
    effect.setOptions({
      zoom: 0.7,
    });
    effect.triggerMouseMove()
  }, 1000);
})
```
