### ISSUE TITLE
Vanta Fog issue with high-dpi screens 

### ISSUE THREAD

**Issue by sigur0r** [tengbao/vanta#60]
Hello. Vanta fog looks great on monitor with 1080p resolution, but when i open it on screens with higher resolution (iphone for example) it lookes uneven. Does anyone know how to fix it?

**Comment by michaeljblum** [comment]
I'm getting the same thing. Fog looks great on Windows at 1080p and even 1440p, but on all my Apple hardware (retina and other high dpi), I'm getting sharp, visible edges to the fog, irregardless of blur value.

**Comment by MaSchVam** [comment]
Hi @sigur0r , I posted a response in #67 with a temporary "fix" for the Fog effect on high DPI screens. It won't quite look the same, but it's serviceable for time being.
