### ISSUE TITLE
Please have a complete demo about vue.js

### ISSUE THREAD

**Issue by blindperson** [tengbao/vanta#63]
When i use it in my project, i put these in index.html use <script> label ，but it will become very stuck,
So i hope there are someone help me.

**Comment by sumbal-coder** [comment]
Hi! I can help you!

**Comment by sumbal-coder** [comment]
/* ----If you are having this issue when vanta is not working you can help from this. I used it in my project---- */
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vanta</title>

    <style>
        body{
            margin: 0;
        }
        #vantajs{
            width: 100%;
            height: 500px;
        }
    </style>

</head>
<body>

<div id="vantajs"></div>






<script src="js/wavesthree.min.js"></script>
<script src="js/vanta.waves.min.js"></script>

<script>
    // - Instilize the plugin by #id selector
        VANTA.WAVES({
        el: "#vantajs",
        wingSpan: 23.00,
        speedLimit: 8.00,
        separation: 60.00,
        alignment: 35.00,
        cohesion: 24.00,
        backgroundAlpha: 0.36,
//You can change the background color code, after 0X six number of code is the color code.
        backgroundColor: 0x0f1c27, 
        color: 0x0f1c27,            //You can also change it custome after 0X.
    });
    // VANTA.WAVES('#vantajs');
    /* code highlight */
    $(document).ready(function(){
        hljs.initHighlightingOnLoad();
    });
</script>
</body>
</html>
[vanta-js.zip](https://github.com/tengbao/vanta/files/4633883/vanta-js.zip)

**Comment by KjetilHaaheim** [comment]
Example using VueJS and Vuetify:

App.vue:
```javascript
<template>
	<v-app id='app'>
		<span class='bg' />

		<v-main>
			<v-container class='pt-16' fill-height>
                                <router-view id='view' />
			</v-container>
		</v-main>
	</v-app>
</template>

<script>
     import * as THREE from 'three'
     import Vanta from 'vanta/dist/vanta.waves.min'

    	mounted() {
		this.vantaEffect = Vanta({
			el: '.bg',
			THREE,
                         // parameters goes here
		})
      }
</script>
```

Replace 'vanta.waves.min' with desired effect.

**Comment by tengbao** [comment]
Added a proper Vue.js example in the readme:

https://github.com/tengbao/vanta/commit/9d45f014b5ffdb8fcbcf83194abc74a471a7d98e
(with refs and destroy method)
