### ISSUE TITLE
THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog Must have an compiled fragment shader attached.

### ISSUE THREAD

**Issue by pjvicari** [tengbao/vanta#71]
Hi! i am trying to implement clouds in my react project, but is not render. i have the next error in console browser:

THREE.WebGLProgram: shader error:  0 35715 false gl.getProgramInfoLog Must have an compiled fragment shader attached. <empty string> THREE.WebGLShader: gl.getShaderInfoLog() fragment
ERROR: 0:125: '=' : global variable initializers must be constant expressions1: #version 300 es

**This is my code in react component:**
`import React, { useRef, useEffect, useState } from 'react'
import PropTypes from 'prop-types'
import Clouds from 'vanta/dist/vanta.clouds.min'
import * as THREE from 'three'

const WelcomeScreen = ({ children }) => {
    const myRefDiv = useRef(null)
    const [vanta, setVanta] = useState(0)

    useEffect(() => {
        if (!vanta) {
            
            setVanta(1)
            
            Clouds({
                THREE,
                el: myRefDiv.current,
            })
        }
        return () => {
            if (vanta) {
                vanta.destroy()
            }
        }

    }, [vanta])
    return (
        <div className="Full" ref={myRefDiv}>
            WelcomeScreen
        </div>
    )
}`

**Comment by tengbao** [comment]
Thanks for the bug report. Fixed in latest release vanta@0.5.18
