### ISSUE TITLE
Getting error while using the birds 

### ISSUE THREAD

**Issue by riyasyash** [tengbao/vanta#74]
I am trying to use the birds with my angular project, and it is giving me this error
`vanta.birds.min.js:1 No OES_texture_float support for float textures.`
Followed by this
`vanta.birds.min.js:1 Uncaught TypeError: Cannot read property 'texture' of undefined
    at r.compute (vanta.birds.min.js:1)
    at M.onUpdate (vanta.birds.min.js:1)
    at M.animationLoop (vanta.birds.min.js:1)
    at new r.VantaBase (vanta.birds.min.js:1)
    at new M (vanta.birds.min.js:1)
    at Object.r.<computed> [as BIRDS] (vanta.birds.min.js:1)
    at (index):17`

**Comment by alexcdot** [comment]
I was also having this problem. Seemed to go away when i used the three.js here: https://github.com/tengbao/vanta/blob/master/vendor/three.r95.min.js instead of here: https://github.com/mrdoob/three.js/blob/dev/build/three.min.js

**Comment by tengbao** [comment]
Thanks for the bug report! I've updated vanta to 0.5.18, which is now compatible with the newest three js (r119).

**Comment by riyasyash** [comment]
Awesome! I will definitely try that out.
