### ISSUE TITLE
Updating color produces no visual change.

### ISSUE THREAD

**Issue by konkrer** [tengbao/vanta#77]
I saw in the documentation that you can update an animation options by calling the setOptions method. I did so and saw that the color2 property was being updated on the animation object. But I see no visual change to the animation displayed. Am I missing something?  Why do I see no change?

I am experimenting with setting the color2 option of the Globe animation to change every 10 seconds.

```
  initHeroAnimation() {
    this.heroAnimation = VANTA.GLOBE({
      el: '.hero-animation',
      mouseControls: true,
      touchControls: true,
      gyroControls: true,
      minHeight: 200.0,
      minWidth: 200.0,
      scale: 1.0,
      scaleMobile: 1.0,
      color: 0xbc7aa,
      color2: 0x8f8f8f,
      size: 1.0,
      backgroundColor: 0x0b105a,
    });

  setInterval(
      function () {
        if (this.heroColorAlt) {
          this.heroAnimation.setOptions({
            color2: 0x8f8f8f,
          });
          this.heroColorAlt = false;
        } else {
          this.heroAnimation.setOptions({
            color2: 0xff6701,
          });
          this.heroColorAlt = true;
        }
      }.bind(this),
      10000
    );
  }
```

**Comment by tengbao** [comment]
Thanks for the bug report. Fixed in 0.5.19 https://github.com/tengbao/vanta/commit/ba06924b50d9a338315a88a1977d321b64124716
