### ISSUE TITLE
Cannot run Vanta Fog with Yarn in Symfony

### ISSUE THREAD

**Issue by Sheitak** [tengbao/vanta#81]
Hello and congratulations on your work,

I've studied your documentation and I'm using the [yarnpkg](https://yarnpkg.com/package/vanta)

I added vanta to my Symfony project and I made calls to it with webpack again

I get "**TypeError: THREE is undefined**"

I forgot something ? Do you have any particular hint on how to integrate vanta with yarn,

Thank you

**Comment by tengbao** [comment]
Are you getting this error in the browser? Or during the build? I might need more details to pinpoint the problem. 

There are two ways to include THREE:

1) Include it as a script in the final HTML file, which loads THREE onto `window`. Then Vanta will just use `window.THREE`.

2) Use a custom build of THREE (see "Using THREE from npm" in the readme), passing into Vanta's initializer function

Either way, also make sure your JS code is not running in the backend (e.g. with SSR).

**Comment by Sheitak** [comment]
Thanks for your response @tengbao,

Yes, the error is present in the browser, I will share a screenshot with you :
![threeundefined](https://user-images.githubusercontent.com/34396292/94825659-b355ed80-0406-11eb-92dc-e9c797ab14ea.png)

For my backend, everything is going well. I installed **Three** and **Vanta** using the command `yarn add vanta` and `yarn add three`

in my JavaScript naming file, my code looks like this :

```
// any CSS you import will output into a single css file (app.css in this case)
import '../css/app.scss';

// JS import
import 'vanta/src/vanta.fog';
import 'three';

// Vanta.js Fog Design
const effect = VANTA.FOG({
    el: "#home-background",
    mouseControls: true,
    touchControls: true,
    gyroControls: false,
    minHeight: 200.00,
    minWidth: 200.00,
    highlightColor: 0x9500ff,
    blurFactor: 0.66,
    speed: 2.00,
    zoom: 1.50
});

```
As you can see I import boasted and he recognizes Fog, only he does not find Three. I tried to integrate various script tags in my **html layout**, I even imported **three.r119.min.js** and **_shaderBase.js**, but without result,

I also tried with **npm**, and I used `import 'THREE' from three` without success,

I'm sure there isn't much missing though,

**Comment by tengbao** [comment]
Since you're importing THREE, did you follow the instructions in the "Using THREE from npm" section of the readme? (see https://github.com/tengbao/vanta/)

Try this:
```
// any CSS you import will output into a single css file (app.css in this case)
import '../css/app.scss';

// JS import
import FOG from 'vanta/src/vanta.fog';
import * as THREE from 'three';

// Vanta.js Fog Design
const effect = FOG({
    el: "#home-background",
    // your effect options here
    THREE: THREE
});
```

**Comment by tengbao** [comment]
@Sheitak Since you're importing THREE, did you follow the instructions in the "Using THREE from npm" section of the readme? (see https://github.com/tengbao/vanta/)

Try this:
```
// any CSS you import will output into a single css file (app.css in this case)
import '../css/app.scss';

// JS import
import FOG from 'vanta/src/vanta.fog';
import * as THREE from 'three';

// Vanta.js Fog Design
const effect = FOG({
    el: "#home-background",
    // your effect options here
    THREE: THREE
});
```

**Comment by Sheitak** [comment]
Okay, great !
It works with your code, my mistake was actually ignoring the use of **Three for npm**, using yarn on my side. The famous `THREE: THREE` was missing,
Thank you very much for your works and time, @tengbao htis is a good job
