### ISSUE TITLE
funtion not woking and no more option

### ISSUE THREAD

**Issue by pjmanikanda** [tengbao/vanta#9]
funtion not woking and no more option.
 also need my clouds direction change. now clouds are comming move. but i need clouds are going movment

**Comment by tengbao** [comment]
@pjmanikanda Can you paste your code into a jsfiddle? I can investigate.

**Comment by tengbao** [comment]
"Clouds going" -- you can try setting a negative `speed`. Added the option here: https://github.com/tengbao/vanta/commit/75e719668b50d32a57668ee82cd26c44f5ab2f32
