### ISSUE TITLE
How to insert in Elementor?

### ISSUE THREAD

**Issue by lucasmaxi** [tengbao/vanta#95]
Hello everyone! I am a **beginning** user of wordpress and the like, I am entering this world now. However, one of my first services, I wanted to insert VANTA.JS as a background and a website. But I can't and I've tried it in many ways.

Basic information, I am using ELEMENTOR PRO.

I wanted to insert the NET background at the beginning of the site but so far I have not been successful. Could someone explain to me? Remembering that I am studying hard and I still don't understand how to insert VANTA.

Since now. Thanks!

**Comment by winniejo** [comment]
I have the same problem only just elementor Basic real pain to get it to work in wordpress...

**Comment by lucasmaxi** [comment]
Hi, are you still having the problem? I managed to solve it, if you need help let me know!

**Comment by winniejo** [comment]
Hey thanks I managed to get it to work also lots of research, do.

**Comment by tengbao** [comment]
Closing this issue for now. @winniejo @lucasmaxi feel free to post your solution here for others.
